import "dotenv/config";
import { db } from "./index";
import { scholarships } from "./schema";

async function seed() {
  console.log("Seeding scholarships…");

  await db
    .insert(scholarships)
    .values([
      // ── NATIONAL (15) ────────────────────────────────────────────────────

      {
        name: "Gates Millennium Scholars Program",
        provider: "Bill & Melinda Gates Foundation",
        providerUrl: "https://www.gmsp.org",
        description:
          "Full scholarship for outstanding minority students with significant financial need pursuing STEM or library science.",
        amountMin: 2000000,
        amountMax: 2500000,
        amountType: "range",
        deadline: "2026-09-15",
        isRecurring: true,
        recurringMonth: 9,
        localityLevel: "national",
        eligibleGpaMin: "3.30",
        eligibleMajors: ["Computer Science", "Engineering", "Mathematics", "Science", "Library Science"],
        eligibleEthnicities: ["African American", "Hispanic", "Native American", "Asian Pacific Islander"],
        eligibleGradeLevels: ["senior", "college_freshman"],
        requiresEssay: true,
        essayWordLimit: 1000,
        estimatedApplicants: 3000,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Coca-Cola Scholars Program",
        provider: "Coca-Cola Scholars Foundation",
        providerUrl: "https://www.coca-colascholarsfoundation.org",
        description:
          "Merit-based scholarship for high-achieving high school seniors who demonstrate leadership and service.",
        amountMin: 2000000,
        amountMax: 2000000,
        amountType: "fixed",
        deadline: "2026-10-31",
        isRecurring: true,
        recurringMonth: 10,
        localityLevel: "national",
        eligibleGpaMin: "3.00",
        eligibleGradeLevels: ["senior"],
        requiresEssay: true,
        essayWordLimit: 800,
        estimatedApplicants: 5000,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Burger King Scholars Program",
        provider: "Burger King McLamore Foundation",
        providerUrl: "https://www.bkmclamorefoundation.org",
        description:
          "Scholarship for students employed in food service, recognizing work ethic alongside academics.",
        amountMin: 100000,
        amountMax: 500000,
        amountType: "range",
        deadline: "2026-12-15",
        isRecurring: true,
        recurringMonth: 12,
        localityLevel: "national",
        eligibleGpaMin: "2.50",
        eligibleGradeLevels: ["senior", "college_freshman", "college_sophomore"],
        eligibleExtracurriculars: ["Food Service", "Restaurant Work"],
        requiresEssay: true,
        essayWordLimit: 400,
        estimatedApplicants: 2000,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Dell Scholars Program",
        provider: "Michael & Susan Dell Foundation",
        providerUrl: "https://www.dellscholars.org",
        description:
          "Comprehensive scholarship and support program for first-generation, low-income students.",
        amountMin: 2000000,
        amountMax: 2000000,
        amountType: "fixed",
        deadline: "2026-12-01",
        isRecurring: true,
        recurringMonth: 12,
        localityLevel: "national",
        eligibleGpaMin: "2.40",
        eligibleGradeLevels: ["senior"],
        eligibleFirstGen: true,
        requiresEssay: true,
        essayWordLimit: 750,
        estimatedApplicants: 4000,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Jackie Robinson Foundation Scholarship",
        provider: "Jackie Robinson Foundation",
        providerUrl: "https://www.jackierobinson.org",
        description:
          "Four-year scholarship for minority students demonstrating exceptional leadership potential.",
        amountMin: 2400000,
        amountMax: 2400000,
        amountType: "fixed",
        deadline: "2026-02-01",
        isRecurring: true,
        recurringMonth: 2,
        localityLevel: "national",
        eligibleGpaMin: "3.00",
        eligibleEthnicities: ["African American", "Hispanic", "Native American", "Asian Pacific Islander"],
        eligibleGradeLevels: ["senior"],
        requiresEssay: true,
        essayWordLimit: 1000,
        estimatedApplicants: 2500,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Ron Brown Scholar Program",
        provider: "Ron Brown Scholar Fund",
        providerUrl: "https://www.ronbrown.org",
        description:
          "Scholarship for African American high school seniors who excel academically and have demonstrated community service.",
        amountMin: 1000000,
        amountMax: 1000000,
        amountType: "fixed",
        deadline: "2026-01-09",
        isRecurring: true,
        recurringMonth: 1,
        localityLevel: "national",
        eligibleGpaMin: "3.00",
        eligibleEthnicities: ["African American"],
        eligibleGradeLevels: ["senior"],
        requiresEssay: true,
        essayWordLimit: 600,
        estimatedApplicants: 1500,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Horatio Alger Association Scholarship",
        provider: "Horatio Alger Association",
        providerUrl: "https://scholars.horatioalger.org",
        description:
          "Need-based scholarship for students who have overcome adversity and demonstrated commitment to higher education.",
        amountMin: 2500000,
        amountMax: 2500000,
        amountType: "fixed",
        deadline: "2026-10-25",
        isRecurring: true,
        recurringMonth: 10,
        localityLevel: "national",
        eligibleGpaMin: "2.00",
        eligibleGradeLevels: ["senior"],
        requiresEssay: true,
        essayWordLimit: 900,
        estimatedApplicants: 3500,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Elks Most Valuable Student Scholarship",
        provider: "Elks National Foundation",
        providerUrl: "https://www.elks.org/scholars",
        description:
          "Merit-based scholarship rewarding academic achievement, leadership, and community service.",
        amountMin: 100000,
        amountMax: 400000,
        amountType: "range",
        deadline: "2026-11-05",
        isRecurring: true,
        recurringMonth: 11,
        localityLevel: "national",
        eligibleGpaMin: "3.00",
        eligibleGradeLevels: ["senior"],
        eligibleCitizenship: ["US Citizen"],
        requiresEssay: true,
        essayWordLimit: 400,
        estimatedApplicants: 3000,
        isActive: true,
        isVerified: true,
      },
      {
        name: "AXA Achievement Scholarship",
        provider: "AXA Foundation",
        providerUrl: "https://us.axa.com/axa-foundation/scholarship",
        description:
          "Recognizes students who demonstrate outstanding achievement in school, community, and workplace.",
        amountMin: 250000,
        amountMax: 250000,
        amountType: "fixed",
        deadline: "2026-12-15",
        isRecurring: true,
        recurringMonth: 12,
        localityLevel: "national",
        eligibleGpaMin: "2.50",
        eligibleGradeLevels: ["sophomore", "junior", "senior"],
        requiresEssay: false,
        estimatedApplicants: 4000,
        isActive: true,
        isVerified: true,
      },
      {
        name: "American Legion Legacy Scholarship",
        provider: "American Legion",
        providerUrl: "https://www.legion.org/scholarships",
        description:
          "Scholarship for children of active-duty military and veterans who died on active service.",
        eligibleMilitaryFamily: true,
        amountMin: 1000000,
        amountMax: 1000000,
        amountType: "fixed",
        deadline: "2026-04-15",
        isRecurring: true,
        recurringMonth: 4,
        localityLevel: "national",
        eligibleGradeLevels: ["junior", "senior", "college_freshman"],
        requiresEssay: true,
        essayWordLimit: 700,
        estimatedApplicants: 1200,
        isActive: true,
        isVerified: true,
      },
      {
        name: "National Merit Scholarship",
        provider: "National Merit Scholarship Corporation",
        providerUrl: "https://www.nationalmerit.org",
        description:
          "Awarded to top PSAT scorers who advance through the national selection process. PSAT is taken junior year.",
        amountMin: 250000,
        amountMax: 250000,
        amountType: "fixed",
        deadline: "2026-10-01",
        isRecurring: true,
        recurringMonth: 10,
        localityLevel: "national",
        eligibleGpaMin: "3.50",
        eligibleGradeLevels: ["junior", "senior"],
        eligibleCitizenship: ["US Citizen"],
        requiresEssay: false,
        estimatedApplicants: 50000,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Tylenol Future Care Scholarship",
        provider: "Tylenol / Johnson & Johnson",
        providerUrl: "https://www.tylenol.com/news/scholarship",
        description:
          "For students pursuing careers in healthcare-related fields.",
        amountMin: 500000,
        amountMax: 1000000,
        amountType: "range",
        deadline: "2026-06-30",
        isRecurring: true,
        recurringMonth: 6,
        localityLevel: "national",
        eligibleMajors: ["Nursing", "Pre-Med", "Public Health", "Pharmacy", "Allied Health"],
        eligibleGradeLevels: ["senior", "college_freshman", "college_sophomore", "college_junior"],
        requiresEssay: true,
        essayWordLimit: 300,
        estimatedApplicants: 2000,
        isActive: true,
        isVerified: true,
      },
      {
        name: "QuestBridge National College Match",
        provider: "QuestBridge",
        providerUrl: "https://www.questbridge.org",
        description:
          "Full four-year scholarship at partner universities for low-income, first-generation students.",
        amountMin: 1500000,
        amountMax: 2500000,
        amountType: "range",
        deadline: "2026-09-26",
        isRecurring: true,
        recurringMonth: 9,
        localityLevel: "national",
        eligibleGpaMin: "3.50",
        eligibleGradeLevels: ["senior"],
        eligibleFirstGen: true,
        requiresEssay: true,
        essayWordLimit: 900,
        estimatedApplicants: 4500,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Prudential Spirit of Community Award",
        provider: "Prudential Financial",
        providerUrl: "https://spirit.prudential.com",
        description:
          "Honors students in grades 5–12 for outstanding volunteer service to their community.",
        amountMin: 100000,
        amountMax: 100000,
        amountType: "fixed",
        deadline: "2026-11-01",
        isRecurring: true,
        recurringMonth: 11,
        localityLevel: "national",
        eligibleGradeLevels: ["freshman", "sophomore", "junior", "senior"],
        eligibleExtracurriculars: ["Volunteering", "Community Service"],
        requiresEssay: false,
        estimatedApplicants: 5000,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Google Lime Scholarship",
        provider: "Google / Lime Connect",
        providerUrl: "https://www.limeconnect.com/opportunities_pool/detail/google-lime-scholarship",
        description:
          "For students with disabilities pursuing degrees in computer science or related technical fields.",
        amountMin: 1000000,
        amountMax: 1000000,
        amountType: "fixed",
        deadline: "2026-12-10",
        isRecurring: true,
        recurringMonth: 12,
        localityLevel: "national",
        eligibleMajors: ["Computer Science", "Software Engineering", "Information Technology"],
        eligibleGradeLevels: ["college_freshman", "college_sophomore", "college_junior"],
        requiresEssay: true,
        essayWordLimit: 400,
        estimatedApplicants: 800,
        isActive: true,
        isVerified: true,
      },

      // ── ARIZONA STATE (15) ───────────────────────────────────────────────

      {
        name: "Flinn Scholarship",
        provider: "Flinn Foundation",
        providerUrl: "https://www.flinn.org/flinn-scholars",
        description:
          "Arizona's most prestigious merit scholarship — full tuition, room, and board at an Arizona public university.",
        amountMin: 1500000,
        amountMax: 2000000,
        amountType: "range",
        deadline: "2026-10-01",
        isRecurring: true,
        recurringMonth: 10,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleGpaMin: "3.50",
        eligibleGradeLevels: ["senior"],
        eligibleCitizenship: ["US Citizen"],
        requiresEssay: true,
        essayWordLimit: 800,
        estimatedApplicants: 400,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Arizona Community Foundation Scholarship",
        provider: "Arizona Community Foundation",
        providerUrl: "https://www.azfoundation.org",
        description:
          "General merit-and-need scholarship for Arizona students at any accredited college or university.",
        amountMin: 200000,
        amountMax: 250000,
        amountType: "range",
        deadline: "2027-01-15",
        isRecurring: true,
        recurringMonth: 1,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman"],
        requiresEssay: false,
        estimatedApplicants: 500,
        isActive: true,
        isVerified: true,
      },
      {
        name: "APS STEM Scholarship",
        provider: "Arizona Public Service Foundation",
        providerUrl: "https://www.aps.com/en/AboutAPS/OurCompany/APS-Foundation",
        description:
          "For Arizona students pursuing engineering, computer science, or math degrees.",
        amountMin: 500000,
        amountMax: 500000,
        amountType: "fixed",
        deadline: "2026-11-30",
        isRecurring: true,
        recurringMonth: 11,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Engineering", "Computer Science", "Mathematics"],
        eligibleGpaMin: "3.00",
        eligibleGradeLevels: ["junior", "senior", "college_freshman"],
        requiresEssay: true,
        essayWordLimit: 400,
        estimatedApplicants: 300,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Salt River Project STEM Scholarship",
        provider: "Salt River Project",
        providerUrl: "https://www.srpnet.com",
        description:
          "Arizona-based utility scholarship for students pursuing STEM degrees at in-state universities.",
        amountMin: 300000,
        amountMax: 300000,
        amountType: "fixed",
        deadline: "2026-12-01",
        isRecurring: true,
        recurringMonth: 12,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Engineering", "Computer Science", "Science", "Mathematics"],
        eligibleGpaMin: "3.00",
        eligibleGradeLevels: ["junior", "senior", "college_freshman", "college_sophomore"],
        requiresEssay: true,
        essayWordLimit: 300,
        estimatedApplicants: 250,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Arizona Nurses Association Scholarship",
        provider: "Arizona Nurses Association",
        providerUrl: "https://www.aznurse.org",
        description:
          "For Arizona nursing students demonstrating academic excellence and commitment to the profession.",
        amountMin: 200000,
        amountMax: 200000,
        amountType: "fixed",
        deadline: "2026-03-31",
        isRecurring: true,
        recurringMonth: 3,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Nursing"],
        eligibleGradeLevels: ["college_freshman", "college_sophomore", "college_junior"],
        requiresEssay: false,
        estimatedApplicants: 150,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Arizona Broadcasters Association Scholarship",
        provider: "Arizona Broadcasters Association",
        providerUrl: "https://www.azbroadcasters.org",
        description:
          "For Arizona students pursuing journalism, broadcasting, or communications majors.",
        amountMin: 150000,
        amountMax: 150000,
        amountType: "fixed",
        deadline: "2026-05-31",
        isRecurring: true,
        recurringMonth: 5,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Journalism", "Broadcasting", "Communications", "Media Studies"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman", "college_sophomore"],
        requiresEssay: false,
        estimatedApplicants: 100,
        isActive: true,
        isVerified: true,
      },
      {
        name: "AZ Association of Family & Consumer Sciences Scholarship",
        provider: "AZ Association of Family & Consumer Sciences",
        providerUrl: "https://www.azafcs.org",
        description:
          "For Arizona students in family and consumer sciences, nutrition, or related fields.",
        amountMin: 100000,
        amountMax: 100000,
        amountType: "fixed",
        deadline: "2026-04-01",
        isRecurring: true,
        recurringMonth: 4,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Nutrition", "Family Studies", "Consumer Sciences", "Education"],
        eligibleGradeLevels: ["college_freshman", "college_sophomore", "college_junior"],
        requiresEssay: false,
        estimatedApplicants: 80,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Arizona Indian Education Association Scholarship",
        provider: "Arizona Indian Education Association",
        providerUrl: "https://www.aieaonline.org",
        description:
          "Supports Native American students in Arizona pursuing higher education.",
        amountMin: 250000,
        amountMax: 250000,
        amountType: "fixed",
        deadline: "2026-05-01",
        isRecurring: true,
        recurringMonth: 5,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleEthnicities: ["Native American"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman", "college_sophomore"],
        requiresEssay: false,
        estimatedApplicants: 120,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Arizona Medical Association Foundation Scholarship",
        provider: "Arizona Medical Association",
        providerUrl: "https://www.azmedassn.org",
        description:
          "For Arizona pre-medical students with strong academics and community service.",
        amountMin: 500000,
        amountMax: 500000,
        amountType: "fixed",
        deadline: "2026-03-15",
        isRecurring: true,
        recurringMonth: 3,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Pre-Med", "Biology", "Chemistry", "Public Health"],
        eligibleGpaMin: "3.20",
        eligibleGradeLevels: ["college_freshman", "college_sophomore", "college_junior"],
        requiresEssay: true,
        essayWordLimit: 400,
        estimatedApplicants: 200,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Maricopa County Education Foundation Award",
        provider: "Maricopa County Education Foundation",
        providerUrl: "https://www.mcef.net",
        description:
          "General scholarship for Maricopa County residents attending Arizona universities.",
        amountMin: 100000,
        amountMax: 100000,
        amountType: "fixed",
        deadline: "2026-02-28",
        isRecurring: true,
        recurringMonth: 2,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman"],
        requiresEssay: false,
        estimatedApplicants: 350,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Arizona Women in Technology Scholarship",
        provider: "Arizona Technology Council",
        providerUrl: "https://www.aztechcouncil.org",
        description:
          "For Arizona women pursuing technology or computer science degrees to close the gender gap in tech.",
        amountMin: 300000,
        amountMax: 300000,
        amountType: "fixed",
        deadline: "2026-11-01",
        isRecurring: true,
        recurringMonth: 11,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Computer Science", "Information Technology", "Software Engineering", "Data Science"],
        eligibleGenders: ["Female"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman", "college_sophomore"],
        requiresEssay: true,
        essayWordLimit: 350,
        estimatedApplicants: 150,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Arizona Builders Alliance Scholarship",
        provider: "Arizona Builders Alliance",
        providerUrl: "https://www.azbuilders.org",
        description:
          "For students pursuing construction management, civil engineering, or related trades in Arizona.",
        amountMin: 200000,
        amountMax: 200000,
        amountType: "fixed",
        deadline: "2026-04-30",
        isRecurring: true,
        recurringMonth: 4,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Construction Management", "Civil Engineering", "Architecture"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman", "college_sophomore"],
        requiresEssay: false,
        estimatedApplicants: 120,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Arizona Society of CPAs Scholarship",
        provider: "Arizona Society of CPAs",
        providerUrl: "https://www.ascpa.com",
        description:
          "Supports Arizona accounting students preparing for careers as Certified Public Accountants.",
        amountMin: 250000,
        amountMax: 250000,
        amountType: "fixed",
        deadline: "2026-03-01",
        isRecurring: true,
        recurringMonth: 3,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Accounting", "Finance"],
        eligibleGpaMin: "3.00",
        eligibleGradeLevels: ["college_sophomore", "college_junior"],
        requiresEssay: false,
        estimatedApplicants: 90,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Arizona Dental Foundation Scholarship",
        provider: "Arizona Dental Foundation",
        providerUrl: "https://www.azdentalfoundation.org",
        description:
          "For Arizona pre-dental students with demonstrated financial need and academic merit.",
        amountMin: 300000,
        amountMax: 300000,
        amountType: "fixed",
        deadline: "2026-06-15",
        isRecurring: true,
        recurringMonth: 6,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Pre-Dental", "Biology", "Chemistry"],
        eligibleGpaMin: "3.00",
        eligibleGradeLevels: ["college_freshman", "college_sophomore", "college_junior"],
        requiresEssay: true,
        essayWordLimit: 350,
        estimatedApplicants: 80,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Helios Education Foundation Scholarship",
        provider: "Helios Education Foundation",
        providerUrl: "https://www.helios.org",
        description:
          "Comprehensive scholarship for first-generation, low-income Arizona students with high potential.",
        amountMin: 500000,
        amountMax: 1000000,
        amountType: "range",
        deadline: "2026-01-31",
        isRecurring: true,
        recurringMonth: 1,
        localityLevel: "state",
        eligibleStates: ["AZ"],
        eligibleGpaMin: "2.50",
        eligibleGradeLevels: ["senior"],
        eligibleFirstGen: true,
        requiresEssay: true,
        essayWordLimit: 700,
        estimatedApplicants: 600,
        isActive: true,
        isVerified: true,
      },

      // ── LOCAL (10) ───────────────────────────────────────────────────────

      {
        name: "Phoenix Community Foundation Scholarship",
        provider: "Phoenix Community Foundation",
        providerUrl: "https://www.phoenixcommunityfoundation.org",
        description:
          "Annual award for Phoenix-area residents demonstrating academic excellence and community involvement.",
        amountMin: 100000,
        amountMax: 100000,
        amountType: "fixed",
        deadline: "2026-03-15",
        isRecurring: true,
        recurringMonth: 3,
        localityLevel: "local",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman"],
        requiresEssay: false,
        estimatedApplicants: 35,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Tucson Community Scholars Award",
        provider: "Tucson Community Education Foundation",
        providerUrl: "https://www.tucsonedfoundation.org",
        description:
          "Supports Tucson-area high school seniors entering college for the first time.",
        amountMin: 75000,
        amountMax: 75000,
        amountType: "fixed",
        deadline: "2026-04-01",
        isRecurring: true,
        recurringMonth: 4,
        localityLevel: "local",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["senior"],
        requiresEssay: false,
        estimatedApplicants: 25,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Scottsdale Arts Education Award",
        provider: "Scottsdale Cultural Council",
        providerUrl: "https://www.scottsdalearts.org",
        description:
          "Awarded to Scottsdale students pursuing fine arts, performing arts, or graphic design.",
        amountMin: 50000,
        amountMax: 50000,
        amountType: "fixed",
        deadline: "2026-05-01",
        isRecurring: true,
        recurringMonth: 5,
        localityLevel: "local",
        eligibleStates: ["AZ"],
        eligibleMajors: ["Fine Arts", "Performing Arts", "Graphic Design", "Music"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman"],
        requiresEssay: false,
        estimatedApplicants: 20,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Mesa Education Foundation Grant",
        provider: "Mesa Education Foundation",
        providerUrl: "https://www.mesaedfoundation.org",
        description:
          "Provides grants to Mesa, Arizona students attending accredited post-secondary institutions.",
        amountMin: 100000,
        amountMax: 100000,
        amountType: "fixed",
        deadline: "2026-03-01",
        isRecurring: true,
        recurringMonth: 3,
        localityLevel: "local",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman"],
        requiresEssay: false,
        estimatedApplicants: 40,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Tempe Community Foundation Award",
        provider: "Tempe Community Foundation",
        providerUrl: "https://www.tempecommunityfoundation.org",
        description:
          "For Tempe residents pursuing higher education with financial need.",
        amountMin: 50000,
        amountMax: 50000,
        amountType: "fixed",
        deadline: "2026-04-15",
        isRecurring: true,
        recurringMonth: 4,
        localityLevel: "local",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["senior"],
        requiresEssay: false,
        estimatedApplicants: 20,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Chandler Education Foundation Scholarship",
        provider: "Chandler Education Foundation",
        providerUrl: "https://www.chandleredfoundation.org",
        description:
          "Scholarship for graduating seniors from Chandler Unified School District.",
        amountMin: 75000,
        amountMax: 75000,
        amountType: "fixed",
        deadline: "2026-02-28",
        isRecurring: true,
        recurringMonth: 2,
        localityLevel: "local",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["junior", "senior"],
        requiresEssay: false,
        estimatedApplicants: 30,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Gilbert Rotary Club Scholarship",
        provider: "Gilbert Rotary Club",
        providerUrl: "https://www.gilbertrotary.org",
        description:
          "Community service scholarship for Gilbert students who have made a positive local impact.",
        amountMin: 100000,
        amountMax: 100000,
        amountType: "fixed",
        deadline: "2026-03-31",
        isRecurring: true,
        recurringMonth: 3,
        localityLevel: "local",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["junior", "senior"],
        requiresEssay: false,
        estimatedApplicants: 25,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Peoria Educational Foundation Scholarship",
        provider: "Peoria Educational Foundation",
        providerUrl: "https://www.peoriaedfoundation.org",
        description:
          "Annual scholarship for students in the Peoria Unified School District.",
        amountMin: 50000,
        amountMax: 50000,
        amountType: "fixed",
        deadline: "2026-03-15",
        isRecurring: true,
        recurringMonth: 3,
        localityLevel: "local",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["senior"],
        requiresEssay: false,
        estimatedApplicants: 20,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Glendale Community Scholars Award",
        provider: "Glendale Community Education Foundation",
        providerUrl: "https://www.glendalecef.org",
        description:
          "For Glendale students who demonstrate academic achievement and community commitment.",
        amountMin: 100000,
        amountMax: 100000,
        amountType: "fixed",
        deadline: "2026-04-30",
        isRecurring: true,
        recurringMonth: 4,
        localityLevel: "local",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman"],
        requiresEssay: false,
        estimatedApplicants: 30,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Surprise Valley Education Grant",
        provider: "Surprise Valley Community Foundation",
        providerUrl: "https://www.surprisefoundation.org",
        description:
          "For residents of Surprise, Arizona entering their first year of college.",
        amountMin: 75000,
        amountMax: 75000,
        amountType: "fixed",
        deadline: "2026-05-15",
        isRecurring: true,
        recurringMonth: 5,
        localityLevel: "local",
        eligibleStates: ["AZ"],
        eligibleGradeLevels: ["senior"],
        requiresEssay: false,
        estimatedApplicants: 18,
        isActive: true,
        isVerified: true,
      },

      // ── NICHE (10) ───────────────────────────────────────────────────────

      {
        name: "LGBTQ+ Future Leaders Fund",
        provider: "Point Foundation",
        providerUrl: "https://www.pointfoundation.org",
        description:
          "Scholarship and mentorship for LGBTQ+ students who demonstrate leadership ability.",
        amountMin: 250000,
        amountMax: 250000,
        amountType: "fixed",
        deadline: "2026-12-01",
        isRecurring: true,
        recurringMonth: 12,
        localityLevel: "national",
        eligibleGenders: ["Non-Binary", "Female"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman", "college_sophomore"],
        requiresEssay: true,
        essayWordLimit: 700,
        estimatedApplicants: 500,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Hispanic Heritage Foundation Youth Award",
        provider: "Hispanic Heritage Foundation",
        providerUrl: "https://www.hispanicheritage.org",
        description:
          "Recognizes Hispanic students who excel academically and contribute to their communities.",
        amountMin: 500000,
        amountMax: 500000,
        amountType: "fixed",
        deadline: "2026-10-01",
        isRecurring: true,
        recurringMonth: 10,
        localityLevel: "national",
        eligibleEthnicities: ["Hispanic"],
        eligibleGpaMin: "3.00",
        eligibleGradeLevels: ["senior"],
        requiresEssay: true,
        essayWordLimit: 600,
        estimatedApplicants: 1200,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Google BOLD Diversity Scholarship",
        provider: "Google",
        providerUrl: "https://buildyourfuture.withgoogle.com/scholarships/google-scholarship-programs",
        description:
          "For underrepresented students in computer science who demonstrate academic achievement and leadership.",
        amountMin: 1000000,
        amountMax: 1500000,
        amountType: "range",
        deadline: "2026-12-01",
        isRecurring: true,
        recurringMonth: 12,
        localityLevel: "national",
        eligibleMajors: ["Computer Science", "Software Engineering", "Data Science"],
        eligibleEthnicities: ["African American", "Hispanic", "Native American"],
        eligibleGradeLevels: ["college_freshman", "college_sophomore", "college_junior"],
        requiresEssay: true,
        essayWordLimit: 800,
        estimatedApplicants: 2000,
        isActive: true,
        isVerified: true,
      },
      {
        name: "American Indian College Fund Scholarship",
        provider: "American Indian College Fund",
        providerUrl: "https://collegefund.org",
        description:
          "Supporting Native American students at tribal colleges and universities across the nation.",
        amountMin: 500000,
        amountMax: 800000,
        amountType: "range",
        deadline: "2026-05-31",
        isRecurring: true,
        recurringMonth: 5,
        localityLevel: "national",
        eligibleEthnicities: ["Native American"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman", "college_sophomore"],
        requiresEssay: true,
        essayWordLimit: 400,
        estimatedApplicants: 800,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Disability Rights Advocates Scholarship",
        provider: "Disability Rights Advocates",
        providerUrl: "https://www.dralegal.org",
        description:
          "For students with disabilities pursuing degrees in law, public policy, or disability studies.",
        amountMin: 300000,
        amountMax: 300000,
        amountType: "fixed",
        deadline: "2026-07-31",
        isRecurring: true,
        recurringMonth: 7,
        localityLevel: "national",
        eligibleMajors: ["Law", "Public Policy", "Political Science", "Disability Studies"],
        eligibleGradeLevels: ["college_sophomore", "college_junior", "college_senior"],
        requiresEssay: true,
        essayWordLimit: 900,
        estimatedApplicants: 200,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Women in STEM Initiative Award",
        provider: "Society of Women Engineers",
        providerUrl: "https://www.swe.org",
        description:
          "Encourages women to enter and advance in engineering, science, and technology fields.",
        amountMin: 500000,
        amountMax: 500000,
        amountType: "fixed",
        deadline: "2026-02-15",
        isRecurring: true,
        recurringMonth: 2,
        localityLevel: "national",
        eligibleMajors: ["Engineering", "Computer Science", "Mathematics", "Science"],
        eligibleGenders: ["Female"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman", "college_sophomore"],
        requiresEssay: true,
        essayWordLimit: 350,
        estimatedApplicants: 1500,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Robotics Team Alumni Scholarship",
        provider: "FIRST Robotics Alumni Association",
        providerUrl: "https://www.firstinspires.org",
        description:
          "For students who participated in FIRST Robotics competitions during high school.",
        amountMin: 100000,
        amountMax: 100000,
        amountType: "fixed",
        deadline: "2026-04-30",
        isRecurring: true,
        recurringMonth: 4,
        localityLevel: "national",
        eligibleExtracurriculars: ["Robotics", "FIRST Robotics"],
        eligibleGradeLevels: ["junior", "senior"],
        requiresEssay: true,
        essayWordLimit: 300,
        estimatedApplicants: 400,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Military Child Education Coalition Scholarship",
        provider: "Military Child Education Coalition",
        providerUrl: "https://www.militarychild.org",
        description:
          "Supporting children of active-duty and veteran military families in pursuing higher education.",
        eligibleMilitaryFamily: true,
        amountMin: 200000,
        amountMax: 200000,
        amountType: "fixed",
        deadline: "2026-03-15",
        isRecurring: true,
        recurringMonth: 3,
        localityLevel: "national",
        eligibleGradeLevels: ["junior", "senior", "college_freshman"],
        requiresEssay: true,
        essayWordLimit: 450,
        estimatedApplicants: 600,
        isActive: true,
        isVerified: true,
      },
      {
        name: "First Generation College Bound Scholarship",
        provider: "First Generation Foundation",
        providerUrl: "https://www.firstgenfoundation.org",
        description:
          "Dedicated to first-generation college students from lower-income households with strong academic records.",
        amountMin: 400000,
        amountMax: 400000,
        amountType: "fixed",
        deadline: "2026-11-15",
        isRecurring: true,
        recurringMonth: 11,
        localityLevel: "national",
        eligibleGpaMin: "2.80",
        eligibleGradeLevels: ["senior"],
        eligibleFirstGen: true,
        requiresEssay: true,
        essayWordLimit: 650,
        estimatedApplicants: 1800,
        isActive: true,
        isVerified: true,
      },
      {
        name: "Environmental Science Leadership Corps",
        provider: "Sierra Club Foundation",
        providerUrl: "https://www.sierraclubfoundation.org",
        description:
          "For students pursuing environmental science, ecology, or sustainability who are active in environmental advocacy.",
        amountMin: 250000,
        amountMax: 250000,
        amountType: "fixed",
        deadline: "2026-08-31",
        isRecurring: true,
        recurringMonth: 8,
        localityLevel: "national",
        eligibleMajors: ["Environmental Science", "Ecology", "Sustainability", "Environmental Studies"],
        eligibleExtracurriculars: ["Environmental Club", "Conservation Volunteer", "Sustainability Club"],
        eligibleGradeLevels: ["junior", "senior", "college_freshman", "college_sophomore"],
        requiresEssay: true,
        essayWordLimit: 750,
        estimatedApplicants: 300,
        isActive: true,
        isVerified: true,
      },
    ])
    .onConflictDoNothing();

  console.log("Done — 50 scholarships seeded.");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
